org: seb34z
app: starton-my-move-api
service: my-move-api
frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs14.x

functions:
  claim:
    handler: src/handler.claim
    events:
      - httpApi:
          path: /
          method: get
